default_platform(:android)

platform :android do
  desc "Fast lane Withe Firebase Distribution"
  lane :firebase_distribution do
  
    sh "flutter clean"

   
    sh "flutter build apk --release  --no-tree-shake-icons"

   
    firebase_app_distribution(
      app: "1:881671348163:android:99c42b35c3270dd209e776",
      release_notes: "App All Features Done Make Final Releases", 
      android_artifact_type: "APK", 
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk", 
      testers: "bigosm654@gmail.com, Merna202112145@gmail.com,nehaleltaweel7@gmail.com,faresseldeen1@gmail.com,lojymoataz81@gmail.com,nancy202112280@gmail.com,Heshambassem202108646@gmail.com,norhan202121668@gmail.com", 
      firebase_cli_token:"1//03CwXG9fweivHCgYIARAAGAMSNwF-L9IrFJalc7738psPoZC5IfsxI3MhQ0oCJSLiCATP-0iEQiYQbHZQEflgyD46DBSzH1h6Drw", 
      
    )
  end
end