name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - master

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2.3"  # Update to the correct Ruby version
        bundler-cache: true
        working-directory: android

    - name: Build and Distribute App
     
      run: |
        cd android  # Change the working directory to "android"
        bundle lock --add-platform x86_64-linux  # Add the platform to the lockfile
        bundle install --jobs 4  # Install dependencies
        bundle exec fastlane android firebase_distribution
